# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.20
# 
# >> macros
# << macros

Name:       libdrm
Summary:    Direct Rendering Manager runtime library
Version:    2.4.25
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://dri.sourceforge.net
Source0:    http://dri.freedesktop.org/libdrm/%{name}-%{version}.tar.bz2
Source100:  libdrm.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(pthread-stubs)


%description
Description: %{summary}


%package devel
Summary:    Direct Rendering Manager development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kernel-headers

%description devel
Description: %{summary}


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
unset LD_AS_NEEDED
# >> build pre
# << build pre

%reconfigure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%doc README
%{_libdir}/libdrm.so.2
%{_libdir}/libdrm.so.2.4.0
%{_libdir}/libdrm_intel.so.1
%{_libdir}/libdrm_intel.so.1.0.0
%{_libdir}/libdrm_radeon.so.1
%{_libdir}/libdrm_radeon.so.1.0.0
%{_libdir}/libkms.so.1
%{_libdir}/libkms.so.1.0.0
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%dir %{_includedir}/libdrm
%{_includedir}/libdrm/drm.h
%{_includedir}/libdrm/drm_sarea.h
%{_includedir}/libdrm/drm_mode.h
%{_includedir}/libdrm/i915_drm.h
%{_includedir}/libdrm/nouveau_drm.h
%{_includedir}/libdrm/mach64_drm.h
%{_includedir}/libdrm/mga_drm.h
%{_includedir}/libdrm/r128_drm.h
%{_includedir}/libdrm/radeon*.h
%{_includedir}/libdrm/savage_drm.h
%{_includedir}/libdrm/sis_drm.h
%{_includedir}/libdrm/via_drm.h
%{_includedir}/xf86drm.h
%{_includedir}/xf86drmMode.h
%{_includedir}/libdrm/intel_bufmgr.h
%{_libdir}/libdrm*.so
%{_libdir}/libdrm_intel.so
%{_libdir}/pkgconfig/libdrm_intel.pc
%{_libdir}/pkgconfig/libdrm.pc
%{_libdir}/pkgconfig/libdrm_radeon.pc
%{_includedir}/libkms/libkms.h
%{_libdir}/libkms.so
%{_libdir}/pkgconfig/libkms.pc
# << files devel

